/**
 * Provenance marker for generated output.
 *
 * Every adapter writes its managed Markdown files through {@link stampGenerated},
 * so the exact string below is the single definition of "this file is ours".
 * Two capabilities depend on it:
 *
 * - `pruneGeneratedFiles()` may only delete a file it recognises as generated;
 *   a marker-less file is never touched, which is how user-authored files in a
 *   managed directory survive (REQ-013 / REQ-051).
 * - `loadAgents()` treats `<workspaceDir>/.opencode/agent/*.md` as a workspace
 *   override. `adapt install --tool opencode` writes its generated agents into
 *   that very directory, so without a way to tell the two apart the loader
 *   re-ingests its own output as input: descriptions gained a quoting layer,
 *   every permission collapsed to `false`, and `adapt uninstall` could no
 *   longer recognise the files it had written (REQ-050).
 */

/** Marks a file as produced by this tool. */
export const GENERATED_MARKER = '<!-- Generated by oh-my-patent. -->';

/** A leading YAML frontmatter block, including the newline that ends it. */
const LEADING_FRONTMATTER = /^(---\r?\n[\s\S]*?\r?\n---)\r?\n?/;

/**
 * Return `content` with the generated marker inserted.
 *
 * The marker goes *after* any YAML frontmatter, never before it: tools that
 * discover agents and skills by reading frontmatter require it to start at byte
 * zero, so a leading comment would break discovery.
 *
 * Idempotent and deterministic — re-stamping a file returns it unchanged, and
 * the same input always produces the same output (CONSTITUTION.md 原则 V).
 */
export function stampGenerated(content: string): string {
  if (content.includes(GENERATED_MARKER)) {
    return content;
  }

  const match = content.match(LEADING_FRONTMATTER);
  if (!match) {
    return `${GENERATED_MARKER}\n${content}`;
  }

  const frontmatter = match[1];
  const body = content.slice(match[0].length);
  return `${frontmatter}\n\n${GENERATED_MARKER}\n${body}`;
}
