/**
 * Pruning support for generated output.
 *
 * `generate()` only ever writes: a file produced by an earlier version of the
 * definition survives every later run, and `uninstall()` cannot remove it
 * either, because its deletion list is derived from the *current* agents,
 * commands and skills. Five legacy agents in a workspace are the measured
 * consequence.
 *
 * Pruning closes that gap, but it must never touch files the user owns. The
 * rule here is deliberately conservative:
 *
 *   a file inside a managed directory is removed only when it is
 *   (a) absent from the current definition's output list, and
 *   (b) recognisably oh-my-patent generated output.
 *
 * Files that fail (b) are reported as preserved, never deleted. A missed
 * cleanup is a smaller problem than a deleted user file.
 */

import { existsSync, readdirSync, readFileSync, rmSync, statSync } from 'fs';
import { join, relative, resolve, sep } from 'path';
import { PortableDef, ToolAdapter } from './types.js';
import { GENERATED_MARKER } from './generated-marker.js';

/**
 * Substrings that mark a file as generated by oh-my-patent.
 *
 * The first entry is the canonical marker every adapter now stamps through
 * `stampGenerated()`. The rest are historical markers, kept so that output
 * written by an older version can still be pruned.
 */
export const GENERATED_MARKERS = [
  GENERATED_MARKER,
  'Generated for Codex by oh-my-patent',
  'Generated for Claude Code by oh-my-patent',
  'Generated fallback skill file for Codex by oh-my-patent',
  'Generated by oh-my-patent',
  '<!-- Agent: ',
  '<!-- Command: ',
  '<!-- Skill: ',
] as const;

/** Whether the given file content was produced by oh-my-patent. */
export function isGeneratedFile(content: string): boolean {
  return GENERATED_MARKERS.some((marker) => content.includes(marker));
}

function toPosix(filePath: string): string {
  return filePath.split(sep).join('/');
}

/** Recursively list files under a directory; unreadable entries are skipped. */
function listFilesRecursive(dir: string): string[] {
  let entries: string[];
  try {
    entries = readdirSync(dir);
  } catch {
    return [];
  }

  const files: string[] = [];
  for (const entry of entries) {
    const full = join(dir, entry);
    let isDirectory = false;
    try {
      isDirectory = statSync(full).isDirectory();
    } catch {
      continue;
    }
    if (isDirectory) {
      files.push(...listFilesRecursive(full));
    } else {
      files.push(full);
    }
  }
  return files;
}

export interface PruneResult {
  /** Generated files that are no longer produced and were deleted. */
  removed: string[];
  /** Files left in place, with the reason: still produced, or not ours. */
  preserved: string[];
}

/**
 * Delete generated files that the current definition no longer produces.
 *
 * @param adapter      Adapter whose managed directories should be scanned
 * @param def          Current portable definition
 * @param workspaceDir Workspace to prune
 * @returns            Relative paths removed, and those deliberately kept
 */
export function pruneGeneratedFiles(
  adapter: ToolAdapter,
  def: PortableDef,
  workspaceDir: string,
): PruneResult {
  const expected = new Set(adapter.getGeneratedFilePaths(def).map(toPosix));
  const removed: string[] = [];
  const preserved: string[] = [];

  for (const relDir of adapter.getManagedDirectories(def)) {
    const absDir = resolve(workspaceDir, relDir);
    if (!existsSync(absDir)) {
      continue;
    }

    for (const absFile of listFilesRecursive(absDir)) {
      const relFile = toPosix(relative(workspaceDir, absFile));
      if (expected.has(relFile)) {
        continue;
      }

      let content: string;
      try {
        content = readFileSync(absFile, 'utf-8');
      } catch {
        preserved.push(relFile);
        continue;
      }

      if (!isGeneratedFile(content)) {
        preserved.push(relFile);
        continue;
      }

      try {
        rmSync(absFile, { force: true });
        removed.push(relFile);
      } catch {
        preserved.push(relFile);
      }
    }
  }

  return { removed, preserved };
}
